// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'soccer_sys';
  static const String PROJECT_VERSION = '1.9.2+20';
  static const String APP_LOGO = 'assets/app_logo.jpg';
  static const String BG = 'assets/bg.jpg';
  static const String RINGTONE = 'assets/sounds/ringtone.wav';
}
