// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class DefaultRes {
  DefaultRes._();

  static const String PROJECT_NAME = 'soccer_sys';
  static const String PROJECT_VERSION = '1.6.9+10';
  static const String = '.env';
}
