// swift-tools-version: 5.9
// Checked in for CI scheme detection. Regenerated by `flutter pub get`.
import PackageDescription

let package = Package(
    name: "FlutterGeneratedPluginSwiftPackage",
    platforms: [
        .iOS("14.0")
    ],
    products: [
        .library(name: "FlutterGeneratedPluginSwiftPackage", type: .static, targets: ["FlutterGeneratedPluginSwiftPackage"])
    ],
    dependencies: [],
    targets: [
        .target(name: "FlutterGeneratedPluginSwiftPackage")
    ]
)
