// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWI7xhk5fVRMvMjWKALn9UuEcQJQiHxo',
    appId: '1:621742273115:web:915f540140c41fc654057e',
    messagingSenderId: '621742273115',
    projectId: 'lifestyle-fit',
    authDomain: 'lifestyle-fit.firebaseapp.com',
    storageBucket: 'lifestyle-fit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcb0ejabR2q_-PkPUDobBiOEM4mptD3s',
    appId: '1:621742273115:android:af44ff2d9449488454057e',
    messagingSenderId: '621742273115',
    projectId: 'lifestyle-fit',
    storageBucket: 'lifestyle-fit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEchqQ5iHN7aJ1Um4z7pSWr6rHLjdwSm0',
    appId: '1:621742273115:ios:a53ecdf7ca9264f354057e',
    messagingSenderId: '621742273115',
    projectId: 'lifestyle-fit',
    storageBucket: 'lifestyle-fit.firebasestorage.app',
    iosBundleId: 'com.sa.lifestylefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEchqQ5iHN7aJ1Um4z7pSWr6rHLjdwSm0',
    appId: '1:621742273115:ios:a53ecdf7ca9264f354057e',
    messagingSenderId: '621742273115',
    projectId: 'lifestyle-fit',
    storageBucket: 'lifestyle-fit.firebasestorage.app',
    iosBundleId: 'com.sa.lifestylefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhWI7xhk5fVRMvMjWKALn9UuEcQJQiHxo',
    appId: '1:621742273115:web:f14a73c54078ef5b54057e',
    messagingSenderId: '621742273115',
    projectId: 'lifestyle-fit',
    authDomain: 'lifestyle-fit.firebaseapp.com',
    storageBucket: 'lifestyle-fit.firebasestorage.app',
  );
}
